export const fallbackVideos = [
  
  
 {
  id: "live-demo",
  title: "NiaTube Live",
  creator: "NiaTube Studio",
  views: 0,
  image: "/niatube-live.jpg",
},
 {
    id: "fallback-lagos-food",
    title: "Street Food in Lagos 🇳🇬",
    creator: "Lagos Vibes",
    views: "12K views",
    image: "/lagos-food.jpg",
    thumbnail_url: "/lagos-food.jpg",
    video_url: null,
    status: "published",
    created_at: "",
    language: "English",
  },
  {
    id: "fallback-kigali-life",
    title: "Life in Kigali 🇷🇼",
    creator: "East Africa Live",
    views: "8.4K views",
    image: "/kigali-life.jpg",
    thumbnail_url: "/kigali-life.jpg",
    video_url: null,
    status: "published",
    created_at: "",
    language: "Swahili",
  },
  {
    id: "fallback-diaspora-london",
    title: "Diaspora Talk: London 🇬🇧",
    creator: "Diaspora Lens",
    views: "5.1K views",
    image: "/diaspora-london.jpg",
    thumbnail_url: "/diaspora-london.jpg",
    video_url: null,
    status: "published",
    created_at: "",
    language: "English",
  },
  {
    id: "fallback-startup-stories",
    title: "African Startup Stories",
    creator: "Nia Business",
    views: "3.9K views",
    image: "/startup-stories.jpg",
    thumbnail_url: "/startup-stories.jpg",
    video_url: null,
    status: "published",
    created_at: "",
    language: "French",
  },
  {
    id: "fallback-politics-weekly",
    title: "Pan-African Politics Weekly",
    creator: "Africa Focus",
    views: "9.2K views",
    image: "/politics-weekly.jpg",
    thumbnail_url: "/politics-weekly.jpg",
    video_url: null,
    status: "published",
    created_at: "",
    language: "French",
  },
];